Josh Lee & Robert Armenta
https://www.kaggle.com/datasets/bkcoban/retail-transaction-dataset

In [ ]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules


import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning, module=r"jupyter_client\..*")

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("bkcoban/retail-transaction-dataset")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/bkcoban/retail-transaction-dataset?dataset_version_number=1...

100%|██████████| 526k/526k [00:00<00:00, 82.7MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/bkcoban/retail-transaction-dataset/versions/1

In [ ]:
from google.colab import files #import files onto google colab
files.upload() #upload file from local drive to google colab

Saving products.csv to products.csv

{'products.csv': b'TransactionID,CustomerID,Products,Timestamp\n1,C546,"Dish Sponge, Flatbread with Meat, Chips, Orange, Butter, Sausage, Cucumber, Rice, Ice Cream",2025-02-18\n2,C385,"Onion, Juice, Flatbread with Meat, Chicken",2025-04-26\n3,C292,"Egg, Flatbread with Meat, Banana, Pizza",2025-04-25\n4,C863,"Ice Cream, Soda, Orange, Potato, Cereal, Chocolate, Cracker",2025-01-14\n5,C171,"Ice Cream, Soap, Shampoo, Chicken, Banana, Beans, Cheese",2025-04-20\n6,C605,"Juice, Shampoo, Bread, Flatbread with Meat, Cracker, Cucumber, Fish",2025-02-21\n7,C215,"Soda, Chocolate, Beans, Juice, Orange, Bread, Tomato, Yogurt, Minced Meat",2025-01-01\n8,C831,"Cookie, Cereal, Sausage, Chips, Chocolate, Lentil, Water, Egg, Cheese",2025-01-17\n9,C919,"Soda, Rice, Soap, Chickpeas",2025-01-24\n10,C512,"Orange, Minced Meat, Chickpeas",2025-04-30\n11,C767,"Milk, Minced Meat, Chips, Chicken, Onion, Cheese, Chickpeas, Cereal",2025-03-22\n12,C453,"Dish Sponge, Onion, Detergent, Egg, Chicken",2025-03-02\n13,C572,"Sausage, Strawberry, Cracker, Pizza",2025-02-09\n14,C964,"Cereal, Minced Meat, Banana, Dish Sponge, Orange",2025-01-28\n15,C237,"Yogurt, Dish Sponge, Butter, Cookie",2025-01-12\n16,C220,"Potato, Chicken, Cucumber, Soda, Butter, Juice",2025-02-28\n17,C977,"Minced Meat, Cereal, Flatbread with Meat, Onion, Honey, Lentil, Cucumber, Orange, Cola, Ice Cream",2025-03-27\n18,C55,"Flatbread with Meat, Juice, Cola",2025-04-04\n19,C357,"Cracker, Sausage, Dumpling, Cookie, Detergent, Chickpeas, Pizza, Banana, Cereal",2025-01-09\n20,C737,"Cracker, Chicken, Tomato, Cola, Shampoo, Cookie, Minced Meat, Yogurt",2025-03-18\n21,C334,"Lentil, Chicken, Yogurt, Onion",2025-04-09\n22,C943,"Minced Meat, Ice Cream, Soap, Cookie",2025-03-10\n23,C478,"Tomato, Apple, Ice Cream, Honey, Fish, Soda, Yogurt",2025-03-14\n24,C239,"Dish Sponge, Minced Meat, Cola, Juice, Flatbread with Meat",2025-01-01\n25,C404,"Strawberry, Egg, Juice, Pizza, Beans, Chickpeas, Cheese, Cola, Minced Meat, Cracker",2025-03-22\n26,C36,"Chocolate, Flatbread with Meat, Detergent, Shampoo, Cucumber, Cola, Sausage, Cheese, Potato",2025-03-29\n27,C113,"Pizza, Bread, Potato, Beans, Butter, Cracker, Chips, Rice, Minced Meat",2025-03-07\n28,C252,"Lentil, Cola, Shampoo, Juice, Strawberry, Bread, Onion, Cucumber",2025-02-02\n29,C175,"Fish, Potato, Cereal, Cookie",2025-01-23\n30,C97,"Banana, Cheese, Chocolate, Butter, Milk, Minced Meat, Honey, Soda, Cereal",2025-03-29\n31,C393,"Egg, Chocolate, Cucumber, Detergent",2025-04-15\n32,C588,"Egg, Honey, Dish Sponge, Cracker, Chickpeas, Minced Meat, Rice, Potato",2025-01-20\n33,C821,"Chips, Flatbread with Meat, Ice Cream, Egg, Chicken",2025-01-12\n34,C317,"Fish, Chickpeas, Potato, Sausage, Flatbread with Meat, Banana, Shampoo, Beans, Cookie, Cheese",2025-01-25\n35,C479,"Chickpeas, Rice, Dumpling, Beans, Yogurt, Cookie",2025-01-03\n36,C296,"Tomato, Water, Pizza, Honey, Shampoo, Lentil, Detergent, Chips, Cracker, Butter",2025-03-21\n37,C153,"Milk, Dish Sponge, Strawberry, Ice Cream, Chickpeas, Shampoo, Soda, Cola, Cheese, Egg",2025-01-20\n38,C94,"Pizza, Water, Yogurt, Potato, Cracker, Rice",2025-04-15\n39,C715,"Chicken, Dumpling, Tomato, Lentil, Cucumber, Cereal, Cookie, Orange",2025-01-30\n40,C365,"Potato, Cookie, Orange, Egg, Beans, Ice Cream",2025-04-21\n41,C959,"Beans, Cereal, Butter, Honey",2025-02-24\n42,C477,"Dumpling, Chocolate, Onion, Soap",2025-03-21\n43,C996,"Sausage, Beans, Ice Cream, Chocolate, Shampoo, Juice, Dish Sponge",2025-04-21\n44,C892,"Cookie, Sausage, Shampoo, Egg, Rice, Water, Dumpling, Onion",2025-03-11\n45,C285,"Yogurt, Cereal, Sausage, Cheese, Bread, Juice, Flatbread with Meat, Strawberry, Ice Cream",2025-02-19\n46,C562,"Chickpeas, Juice, Orange",2025-02-01\n47,C377,"Cracker, Tomato, Beans, Orange, Ice Cream, Lentil",2025-02-02\n48,C106,"Chips, Potato, Honey, Chocolate",2025-02-04\n49,C291,"Banana, Lentil, Apple, Cola, Pizza, Shampoo, Juice, Dish Sponge, Sausage",2025-02-24\n50,C309,"Dumpling, Onion, Cereal, Butter, Detergent, Banana, Water, Chocolate, Cucumber, Milk",2025-03-01\n51,C64,"Egg, Strawberry, Cracker, Dish Sponge, Potato",2025-03-08\n52,C956,"Sausage, Strawberry, Yogurt, Chicken",2025-02-12\n53,C65,"Ice Cream, Tomato, Rice",2025-03-18\n54,C891,"Bread, Onion, Minced Meat",2025-01-06\n55,C618,"Bread, Chocolate, Sausage, Fish, Cookie, Dumpling",2025-01-05\n56,C713,"Cheese, Chicken, Dumpling, Flatbread with Meat, Cereal, Milk, Minced Meat, Tomato",2025-01-10\n57,C337,"Flatbread with Meat, Minced Meat, Yogurt, Apple, Orange, Chicken, Egg",2025-03-02\n58,C402,"Potato, Cucumber, Soda, Juice, Beans, Cereal, Cheese, Bread, Lentil, Chicken",2025-04-03\n59,C165,"Honey, Potato, Pizza, Beans, Cola, Fish, Lentil",2025-03-19\n60,C496,"Banana, Dumpling, Cheese, Milk, Apple, Beans, Cereal",2025-02-10\n61,C369,"Detergent, Chips, Strawberry, Chickpeas, Bread, Rice, Milk, Onion, Yogurt, Cola",2025-02-12\n62,C545,"Strawberry, Cola, Cereal, Cracker, Rice, Lentil, Beans, Ice Cream, Dumpling, Yogurt",2025-02-06\n63,C83,"Soda, Strawberry, Minced Meat",2025-03-07\n64,C281,"Cookie, Potato, Cheese, Beans, Chocolate, Shampoo, Egg",2025-01-04\n65,C142,"Potato, Butter, Ice Cream",2025-03-24\n66,C887,"Detergent, Apple, Tomato, Water, Strawberry, Rice",2025-02-21\n67,C887,"Water, Soap, Dumpling, Chickpeas, Chocolate, Cucumber, Minced Meat, Beans, Strawberry, Pizza",2025-01-19\n68,C381,"Bread, Dumpling, Strawberry",2025-04-29\n69,C521,"Tomato, Orange, Chips, Water, Beans, Dumpling, Cookie, Chocolate",2025-01-12\n70,C22,"Minced Meat, Lentil, Cracker, Butter, Rice, Sausage, Yogurt, Cookie, Tomato",2025-04-30\n71,C453,"Cola, Banana, Chicken, Cereal, Soda, Beans, Onion",2025-03-20\n72,C464,"Chips, Soda, Chickpeas, Soap, Honey, Chocolate",2025-01-18\n73,C329,"Pizza, Yogurt, Egg, Dish Sponge, Chickpeas, Orange, Water, Cracker, Cola",2025-01-09\n74,C445,"Bread, Soda, Honey, Chocolate, Egg, Apple, Lentil, Pizza, Orange, Rice",2025-03-30\n75,C747,"Dish Sponge, Lentil, Apple, Cheese",2025-04-12\n76,C455,"Minced Meat, Cereal, Tomato, Chocolate, Egg, Banana, Onion, Flatbread with Meat, Juice, Soap",2025-03-06\n77,C96,"Strawberry, Onion, Soda, Chicken, Yogurt",2025-01-10\n78,C688,"Fish, Honey, Egg",2025-04-27\n79,C887,"Water, Butter, Honey, Cucumber, Egg, Soda, Milk, Apple, Strawberry, Cookie, Cereal",2025-02-22\n80,C402,"Ice Cream, Sausage, Cucumber, Milk, Soap, Apple, Strawberry, Orange, Water",2025-01-15\n81,C413,"Pizza, Water, Chocolate, Detergent, Soap",2025-03-15\n82,C283,"Pizza, Bread, Rice, Ice Cream, Dumpling, Sausage",2025-02-04\n83,C485,"Apple, Strawberry, Yogurt, Cucumber, Rice",2025-03-04\n84,C276,"Cereal, Rice, Yogurt",2025-04-06\n85,C571,"Ice Cream, Egg, Chips, Juice, Strawberry, Onion, Chickpeas, Apple",2025-02-06\n86,C174,"Cucumber, Ice Cream, Sausage",2025-03-01\n87,C250,"Cereal, Ice Cream, Shampoo, Flatbread with Meat, Butter, Banana, Strawberry, Egg",2025-04-12\n88,C162,"Fish, Soap, Detergent, Lentil, Yogurt, Sausage, Tomato, Cookie, Cracker, Apple",2025-03-31\n89,C370,"Cheese, Ice Cream, Bread, Apple, Orange, Shampoo, Lentil, Honey",2025-01-25\n90,C134,"Yogurt, Pizza, Cheese, Cola, Dumpling, Minced Meat, Chips",2025-03-14\n91,C147,"Dumpling, Cracker, Cookie, Strawberry, Rice",2025-01-22\n92,C779,"Orange, Minced Meat, Rice, Potato",2025-04-04\n93,C387,"Soap, Chips, Juice, Rice, Cola, Ice Cream, Chocolate, Minced Meat, Orange, Cucumber",2025-04-06\n94,C989,"Lentil, Butter, Potato, Soda, Chicken",2025-04-09\n95,C410,"Cracker, Chickpeas, Onion, Milk, Shampoo, Egg",2025-04-20\n96,C358,"Bread, Milk, Dish Sponge, Dumpling, Cola, Soda, Cookie, Cereal",2025-04-07\n97,C157,"Cookie, Cheese, Apple, Detergent, Strawberry, Soda, Banana, Tomato, Chickpeas, Potato",2025-02-03\n98,C999,"Honey, Apple, Potato, Cola, Soda, Dumpling, Ice Cream, Chips, Dish Sponge, Flatbread with Meat",2025-03-31\n99,C302,"Chocolate, Sausage, Pizza, Shampoo, Dumpling",2025-04-06\n100,C769,"Fish, Detergent, Honey, Water, Flatbread with Meat, Cucumber",2025-03-01\n101,C93,"Orange, Chips, Cheese, Cracker",2025-02-04\n102,C373,"Potato, Tomato, Flatbread with Meat, Dumpling, Honey, Soap, Detergent, Dish Sponge",2025-01-02\n103,C680,"Chips, Shampoo, Soda",2025-02-18\n104,C853,"Cracker, Banana, Soap, Cereal, Onion, Milk, Detergent, Beans",2025-01-09\n105,C892,"Cheese, Soap, Milk",2025-02-01\n106,C258,"Cereal, Yogurt, Beans, Fish, Banana, Cola, Minced Meat, Strawberry, Sausage, Egg",2025-03-25\n107,C525,"Apple, Soda, Minced Meat, Dish Sponge, Rice, Sausage",2025-01-26\n108,C897,"Chips, Orange, Yogurt, Rice, Shampoo, Soap",2025-01-20\n109,C677,"Cracker, Soda, Flatbread with Meat, Onion, Tomato, Minced Meat, Bread, Apple, Cheese, Yogurt",2025-02-27\n110,C573,"Strawberry, Juice, Cheese, Chips, Fish, Cookie",2025-04-23\n111,C750,"Cheese, Minced Meat, Water, Dish Sponge, Dumpling, Soda, Yogurt, Honey, Fish",2025-02-03\n112,C319,"Cola, Fish, Bread, Chocolate, Juice, Soap",2025-03-22\n113,C45,"Tomato, Apple, Chickpeas",2025-02-04\n114,C766,"Cracker, Dumpling, Soda, Milk, Egg, Chocolate, Lentil",2025-01-05\n115,C377,"Apple, Honey, Chickpeas, Soap",2025-03-06\n116,C762,"Orange, Yogurt, Soda, Cracker, Honey, Chips, Soap, Egg",2025-02-05\n117,C954,"Butter, Lentil, Tomato, Ice Cream, Onion, Pizza, Sausage, Cracker, Cola",2025-01-07\n118,C418,"Pizza, Butter, Cereal, Soda, Lentil",2025-01-06\n119,C962,"Potato, Flatbread with Meat, Dumpling, Chickpeas, Strawberry, Onion, Pizza, Fish",2025-04-09\n120,C167,"Milk, Ice Cream, Yogurt, Juice, Apple, Cola, Cereal",2025-03-13\n121,C656,"Sausage, Cookie, Cereal",2025-03-18\n122,C310,"Orange, Rice, Egg, Onion, Soda",2025-04-26\n123,C760,"Pizza, Dumpling, Detergent",2025-03-26\n124,C776,"Potato, Dumpling, Yogurt, Sausage, Banana, Chocolate",2025-03-11\n125,C120,"Water, Juice, Cucumber, Tomato, Chicken, Onion, Pizza, Rice, Detergent, Butter",2025-02-18\n126,C654,"Yogurt, Onion, Chickpeas, Chips, Strawberry, Juice, Detergent, Butter, Dumpling, Cola",2025-03-18\n127,C244,"Water, Apple, Butter, Chickpeas, Tomato, Detergent, Pizza",2025-04-12\n128,C230,"Milk, Shampoo, Minced Meat, Beans, Pizza, Chicken, Tomato, Apple, Dish Sponge",2025-03-14\n129,C575,"Sausage, Banana, Soap, Cola",2025-01-24\n130,C658,"Sausage, Strawberry, Chocolate, Dumpling, Chicken, Chickpeas, Tomato, Juice",2025-04-08\n131,C18,"Chocolate, Milk, Juice",2025-04-28\n132,C425,"Milk, Potato, Chips, Dumpling",2025-02-02\n133,C759,"Cheese, Honey, Potato, Sausage",2025-03-03\n134,C432,"Yogurt, Strawberry, Pizza, Rice, Egg, Juice, Lentil, Onion, Potato",2025-01-20\n135,C79,"Butter, Banana, Shampoo, Chips, Cucumber",2025-02-15\n136,C340,"Tomato, Ice Cream, Cereal, Chips, Chicken, Beans",2025-03-31\n137,C125,"Cereal, Chickpeas, Soap, Pizza, Chicken, Water, Egg, Honey",2025-04-24\n138,C488,"Tomato, Cola, Beans, Fish, Minced Meat",2025-04-11\n139,C462,"Orange, Cucumber, Honey",2025-04-25\n140,C812,"Apple, Cheese, Milk, Cookie, Lentil, Cracker, Detergent, Orange, Minced Meat, Cereal",2025-04-08\n141,C25,"Bread, Rice, Water, Chickpeas, Flatbread with Meat, Soap, Pizza, Potato, Detergent, Dumpling",2025-04-05\n142,C363,"Chips, Soda, Rice, Dish Sponge, Bread, Shampoo, Potato, Chocolate",2025-02-05\n143,C633,"Honey, Onion, Potato, Soda, Cucumber, Tomato, Chips, Cola",2025-02-27\n144,C770,"Fish, Juice, Lentil",2025-03-28\n145,C584,"Apple, Sausage, Pizza, Chips, Cookie, Bread, Juice",2025-02-08\n146,C955,"Chips, Apple, Potato, Yogurt, Minced Meat, Honey",2025-01-10\n147,C948,"Flatbread with Meat, Honey, Chickpeas, Yogurt, Dumpling, Cheese, Cracker, Detergent, Ice Cream, Potato",2025-02-06\n148,C569,"Chickpeas, Chocolate, Egg",2025-03-06\n149,C366,"Chocolate, Butter, Cheese, Lentil, Honey, Rice, Bread",2025-02-16\n150,C812,"Dish Sponge, Milk, Onion, Minced Meat, Beans, Sausage, Soda, Honey, Cereal",2025-03-23\n151,C225,"Shampoo, Beans, Strawberry, Chicken, Orange, Dumpling, Pizza, Detergent, Minced Meat, Chips",2025-02-13\n152,C118,"Dumpling, Rice, Strawberry, Banana, Detergent, Minced Meat",2025-03-02\n153,C669,"Yogurt, Honey, Beans, Chocolate, Detergent, Fish, Cola, Dumpling",2025-03-12\n154,C630,"Strawberry, Detergent, Chicken, Egg",2025-03-15\n155,C238,"Beans, Bread, Chocolate, Orange, Soda, Egg, Honey, Flatbread with Meat, Cereal",2025-04-21\n156,C726,"Dish Sponge, Dumpling, Cracker, Cheese",2025-02-04\n157,C847,"Soda, Beans, Strawberry, Cracker, Cucumber, Milk, Cereal, Chips",2025-04-05\n158,C452,"Yogurt, Lentil, Flatbread with Meat",2025-01-26\n159,C530,"Milk, Chocolate, Cola, Sausage, Shampoo",2025-03-04\n160,C457,"Tomato, Rice, Banana, Water, Soda, Cookie, Chips, Cola, Chicken",2025-02-26\n161,C994,"Chicken, Cola, Cucumber, Chocolate, Lentil",2025-01-12\n162,C297,"Honey, Cereal, Yogurt, Dish Sponge, Rice",2025-01-22\n163,C629,"Onion, Chickpeas, Bread, Egg, Cucumber, Minced Meat, Potato",2025-03-19\n164,C336,"Bread, Chocolate, Fish, Cracker, Cookie",2025-02-27\n165,C115,"Cucumber, Orange, Apple, Minced Meat, Lentil, Soda, Chips",2025-03-06\n166,C608,"Bread, Cracker, Minced Meat, Apple",2025-04-07\n167,C830,"Butter, Water, Egg, Detergent, Banana, Strawberry, Soap, Rice",2025-02-05\n168,C968,"Strawberry, Bread, Shampoo, Soap, Beans, Sausage, Lentil, Soda, Fish, Chocolate",2025-03-24\n169,C589,"Shampoo, Lentil, Soap, Cookie, Banana",2025-04-26\n170,C842,"Lentil, Tomato, Cereal, Detergent, Strawberry, Cucumber",2025-03-08\n171,C315,"Shampoo, Detergent, Cereal, Beans, Chickpeas",2025-03-27\n172,C927,"Butter, Chips, Flatbread with Meat, Ice Cream, Fish, Onion, Pizza, Milk",2025-04-27\n173,C804,"Butter, Detergent, Bread, Dish Sponge, Chickpeas, Banana, Juice, Cheese, Shampoo, Tomato",2025-01-01\n174,C834,"Cola, Juice, Fish, Cheese, Cookie, Flatbread with Meat, Soda",2025-04-17\n175,C746,"Lentil, Chips, Butter, Ice Cream, Cheese, Cucumber, Cola, Dumpling",2025-01-03\n176,C332,"Orange, Juice, Soda, Water, Apple",2025-03-20\n177,C808,"Ice Cream, Honey, Rice, Chicken, Chocolate, Strawberry, Shampoo, Detergent, Minced Meat",2025-02-02\n178,C780,"Tomato, Cheese, Cucumber",2025-03-27\n179,C19,"Chickpeas, Tomato, Honey, Chocolate, Yogurt, Chips, Beans",2025-03-01\n180,C799,"Lentil, Chickpeas, Cracker, Soap, Juice, Chocolate, Tomato, Pizza, Cola, Onion",2025-04-13\n181,C311,"Honey, Strawberry, Yogurt",2025-03-29\n182,C624,"Bread, Ice Cream, Apple, Dumpling, Milk, Dish Sponge, Shampoo, Cucumber, Honey, Beans",2025-03-31\n183,C483,"Detergent, Rice, Minced Meat",2025-04-29\n184,C597,"Yogurt, Bread, Tomato, Cracker, Pizza, Cucumber, Soda",2025-01-07\n185,C776,"Dish Sponge, Water, Ice Cream, Orange, Honey, Yogurt, Minced Meat",2025-01-13\n186,C131,"Minced Meat, Fish, Water, Onion, Yogurt, Apple",2025-03-27\n187,C17,"Cola, Dish Sponge, Pizza, Potato, Cucumber, Beans, Bread, Lentil",2025-04-27\n188,C571,"Cucumber, Milk, Dish Sponge, Cola, Beans, Cereal",2025-04-28\n189,C575,"Orange, Yogurt, Shampoo, Lentil, Bread, Cracker, Cheese, Chickpeas, Juice, Chocolate",2025-01-23\n190,C868,"Cereal, Milk, Pizza, Rice, Soap, Banana, Potato, Cucumber, Beans",2025-03-07\n191,C33,"Sausage, Fish, Lentil",2025-03-25\n192,C289,"Water, Tomato, Cookie, Cola, Chickpeas",2025-02-28\n193,C10,"Water, Banana, Soap, Flatbread with Meat, Fish, Lentil, Tomato, Egg",2025-02-09\n194,C601,"Dish Sponge, Shampoo, Cookie, Honey, Chips, Cola",2025-01-01\n195,C179,"Bread, Water, Beans, Dumpling",2025-03-16\n196,C492,"Rice, Cheese, Water, Yogurt, Fish, Minced Meat, Strawberry, Onion",2025-01-14\n197,C746,"Potato, Cola, Yogurt, Detergent, Rice, Cheese, Shampoo, Strawberry, Milk, Dish Sponge",2025-02-08\n198,C450,"Soap, Juice, Flatbread with Meat, Chips",2025-01-17\n199,C770,"Strawberry, Apple, Chickpeas, Soap, Flatbread with Meat, Potato, Butter, Chicken, Juice, Sausage",2025-02-19\n200,C293,"Chickpeas, Cookie, Potato, Fish, Sausage, Lentil, Minced Meat, Cheese",2025-02-02\n201,C305,"Cola, Shampoo, Banana",2025-04-09\n202,C556,"Bread, Soda, Cucumber, Cola, Honey, Sausage, Potato",2025-01-24\n203,C250,"Tomato, Ice Cream, Apple",2025-01-18\n204,C372,"Water, Potato, Chickpeas",2025-01-04\n205,C710,"Banana, Chips, Dumpling, Beans, Cookie, Egg, Detergent, Strawberry, Honey, Cola",2025-02-10\n206,C465,"Cookie, Butter, Minced Meat, Dish Sponge, Cracker, Detergent, Beans, Soda, Chickpeas, Water",2025-03-04\n207,C920,"Shampoo, Rice, Cheese, Fish, Juice, Water, Ice Cream, Honey",2025-01-03\n208,C575,"Chips, Detergent, Ice Cream, Tomato, Cracker",2025-03-30\n209,C329,"Orange, Ice Cream, Flatbread with Meat, Chips, Cracker",2025-03-17\n210,C624,"Chocolate, Soda, Onion, Juice, Cookie, Lentil, Cereal",2025-01-11\n211,C475,"Bread, Water, Rice, Cereal, Lentil, Chips, Yogurt, Minced Meat, Soap",2025-01-21\n212,C866,"Bread, Cookie, Flatbread with Meat, Dish Sponge, Cola",2025-02-04\n213,C186,"Egg, Milk, Chips, Soda, Apple, Cheese, Cereal",2025-01-27\n214,C214,"Cereal, Dumpling, Soap, Minced Meat, Chocolate, Butter, Honey, Onion, Chicken, Chickpeas",2025-01-22\n215,C169,"Soda, Chicken, Rice, Honey, Butter, Juice, Cola, Dish Sponge, Egg",2025-01-28\n216,C755,"Cheese, Ice Cream, Cereal, Cookie, Cracker",2025-03-14\n217,C476,"Butter, Egg, Chips, Juice",2025-02-17\n218,C655,"Milk, Cheese, Orange, Yogurt",2025-03-03\n219,C112,"Honey, Detergent, Beans, Milk, Cheese, Dish Sponge, Rice, Fish, Butter, Juice, Cereal",2025-02-07\n220,C786,"Detergent, Chicken, Banana",2025-03-03\n221,C828,"Egg, Chocolate, Cola, Strawberry, Dumpling",2025-04-30\n222,C353,"Strawberry, Milk, Dumpling, Pizza, Rice, Soda, Orange, Chicken, Juice",2025-02-25\n223,C914,"Juice, Beans, Yogurt",2025-01-18\n224,C792,"Dish Sponge, Cola, Ice Cream, Dumpling, Shampoo, Fish",2025-01-12\n225,C507,"Flatbread with Meat, Cookie, Cola, Water, Chickpeas, Juice",2025-04-27\n226,C816,"Chickpeas, Tomato, Rice, Bread, Cola, Strawberry",2025-02-01\n227,C185,"Cookie, Apple, Chips, Soda, Soap, Juice, Beans, Pizza, Onion",2025-04-06\n228,C935,"Bread, Water, Chocolate, Dish Sponge, Milk, Honey, Cheese, Potato, Cereal",2025-03-08\n229,C758,"Egg, Apple, Chickpeas, Flatbread with Meat, Cookie, Butter, Yogurt, Water, Fish",2025-04-09\n230,C689,"Water, Flatbread with Meat, Soap, Apple, Strawberry, Dish Sponge, Milk, Butter, Detergent, Cereal",2025-03-26\n231,C9,"Minced Meat, Potato, Cracker",2025-02-10\n232,C723,"Water, Onion, Cheese",2025-03-01\n233,C380,"Onion, Apple, Cola, Strawberry, Dumpling, Cucumber",2025-03-19\n234,C310,"Bread, Strawberry, Butter, Detergent",2025-01-29\n235,C247,"Shampoo, Juice, Ice Cream, Sausage, Apple, Beans, Cracker",2025-01-01\n236,C876,"Shampoo, Cola, Chocolate, Juice, Minced Meat, Chips, Strawberry, Cereal",2025-02-18\n237,C99,"Lentil, Cola, Ice Cream, Flatbread with Meat, Cucumber, Shampoo, Beans",2025-01-18\n238,C979,"Beans, Cereal, Chocolate, Cola, Apple, Chickpeas, Yogurt, Juice, Lentil",2025-03-08\n239,C283,"Cracker, Potato, Dumpling, Ice Cream, Strawberry",2025-02-24\n240,C458,"Honey, Chicken, Strawberry, Flatbread with Meat, Ice Cream, Detergent, Lentil, Orange, Shampoo",2025-03-17\n241,C463,"Lentil, Onion, Cheese",2025-02-03\n242,C810,"Flatbread with Meat, Cereal, Dish Sponge, Water, Butter, Ice Cream, Orange",2025-02-03\n243,C806,"Juice, Flatbread with Meat, Cracker, Lentil, Minced Meat, Honey",2025-02-14\n244,C412,"Egg, Cracker, Potato",2025-04-16\n245,C964,"Water, Shampoo, Cola, Tomato, Rice, Lentil, Banana",2025-03-17\n246,C476,"Butter, Potato, Fish, Juice, Chips",2025-01-01\n247,C543,"Cucumber, Potato, Water, Shampoo, Honey, Banana, Minced Meat, Chocolate, Dumpling",2025-01-30\n248,C634,"Yogurt, Chocolate, Soap, Onion, Dish Sponge, Rice, Juice, Chips",2025-04-01\n249,C109,"Honey, Chickpeas, Butter, Cola, Pizza, Chocolate, Lentil",2025-01-03\n250,C322,"Cola, Tomato, Cheese, Banana, Egg",2025-03-18\n251,C226,"Tomato, Juice, Minced Meat, Detergent, Soap, Chips, Onion, Orange, Fish",2025-01-19\n252,C156,"Butter, Chicken, Pizza, Tomato, Cola, Egg",2025-01-31\n253,C7,"Cookie, Onion, Water, Strawberry, Apple, Minced Meat",2025-03-24\n254,C813,"Juice, Tomato, Detergent, Chocolate, Soda, Cucumber, Minced Meat, Apple, Cola",2025-02-17\n255,C889,"Cola, Dish Sponge, Detergent, Beans, Dumpling",2025-01-30\n256,C453,"Onion, 

In [ ]:
df=pd.read_csv('products.csv')
df.head()

,TransactionID,CustomerID,Products,Timestamp
0,1,C546,"Dish Sponge, Flatbread with Meat, Chips, Orang...",2025-02-18
1,2,C385,"Onion, Juice, Flatbread with Meat, Chicken",2025-04-26
2,3,C292,"Egg, Flatbread with Meat, Banana, Pizza",2025-04-25
3,4,C863,"Ice Cream, Soda, Orange, Potato, Cereal, Choco...",2025-01-14
4,5,C171,"Ice Cream, Soap, Shampoo, Chicken, Banana, Bea...",2025-04-20

In [ ]:
df.shape

(30000, 4)

In [ ]:
data=list(df["Products"].apply(lambda x:x.split(",")))
data

[['Dish Sponge',
  ' Flatbread with Meat',
  ' Chips',
  ' Orange',
  ' Butter',
  ' Sausage',
  ' Cucumber',
  ' Rice',
  ' Ice Cream'],
 ['Onion', ' Juice', ' Flatbread with Meat', ' Chicken'],
 ['Egg', ' Flatbread with Meat', ' Banana', ' Pizza'],
 ['Ice Cream',
  ' Soda',
  ' Orange',
  ' Potato',
  ' Cereal',
  ' Chocolate',
  ' Cracker'],
 ['Ice Cream',
  ' Soap',
  ' Shampoo',
  ' Chicken',
  ' Banana',
  ' Beans',
  ' Cheese'],
 ['Juice',
  ' Shampoo',
  ' Bread',
  ' Flatbread with Meat',
  ' Cracker',
  ' Cucumber',
  ' Fish'],
 ['Soda',
  ' Chocolate',
  ' Beans',
  ' Juice',
  ' Orange',
  ' Bread',
  ' Tomato',
  ' Yogurt',
  ' Minced Meat'],
 ['Cookie',
  ' Cereal',
  ' Sausage',
  ' Chips',
  ' Chocolate',
  ' Lentil',
  ' Water',
  ' Egg',
  ' Cheese'],
 ['Soda', ' Rice', ' Soap', ' Chickpeas'],
 ['Orange', ' Minced Meat', ' Chickpeas'],
 ['Milk',
  ' Minced Meat',
  ' Chips',
  ' Chicken',
  ' Onion',
  ' Cheese',
  ' Chickpeas',
  ' Cereal'],
 ['Dish Sponge', ' Onion', ' Detergent', ' Egg', ' Chicken'],
 ['Sausage', ' Strawberry', ' Cracker', ' Pizza'],
 ['Cereal', ' Minced Meat', ' Banana', ' Dish Sponge', ' Orange'],
 ['Yogurt', ' Dish Sponge', ' Butter', ' Cookie'],
 ['Potato', ' Chicken', ' Cucumber', ' Soda', ' Butter', ' Juice'],
 ['Minced Meat',
  ' Cereal',
  ' Flatbread with Meat',
  ' Onion',
  ' Honey',
  ' Lentil',
  ' Cucumber',
  ' Orange',
  ' Cola',
  ' Ice Cream'],
 ['Flatbread with Meat', ' Juice', ' Cola'],
 ['Cracker',
  ' Sausage',
  ' Dumpling',
  ' Cookie',
  ' Detergent',
  ' Chickpeas',
  ' Pizza',
  ' Banana',
  ' Cereal'],
 ['Cracker',
  ' Chicken',
  ' Tomato',
  ' Cola',
  ' Shampoo',
  ' Cookie',
  ' Minced Meat',
  ' Yogurt'],
 ['Lentil', ' Chicken', ' Yogurt', ' Onion'],
 ['Minced Meat', ' Ice Cream', ' Soap', ' Cookie'],
 ['Tomato', ' Apple', ' Ice Cream', ' Honey', ' Fish', ' Soda', ' Yogurt'],
 ['Dish Sponge', ' Minced Meat', ' Cola', ' Juice', ' Flatbread with Meat'],
 ['Strawberry',
  ' Egg',
  ' Juice',
  ' Pizza',
  ' Beans',
  ' Chickpeas',
  ' Cheese',
  ' Cola',
  ' Minced Meat',
  ' Cracker'],
 ['Chocolate',
  ' Flatbread with Meat',
  ' Detergent',
  ' Shampoo',
  ' Cucumber',
  ' Cola',
  ' Sausage',
  ' Cheese',
  ' Potato'],
 ['Pizza',
  ' Bread',
  ' Potato',
  ' Beans',
  ' Butter',
  ' Cracker',
  ' Chips',
  ' Rice',
  ' Minced Meat'],
 ['Lentil',
  ' Cola',
  ' Shampoo',
  ' Juice',
  ' Strawberry',
  ' Bread',
  ' Onion',
  ' Cucumber'],
 ['Fish', ' Potato', ' Cereal', ' Cookie'],
 ['Banana',
  ' Cheese',
  ' Chocolate',
  ' Butter',
  ' Milk',
  ' Minced Meat',
  ' Honey',
  ' Soda',
  ' Cereal'],
 ['Egg', ' Chocolate', ' Cucumber', ' Detergent'],
 ['Egg',
  ' Honey',
  ' Dish Sponge',
  ' Cracker',
  ' Chickpeas',
  ' Minced Meat',
  ' Rice',
  ' Potato'],
 ['Chips', ' Flatbread with Meat', ' Ice Cream', ' Egg', ' Chicken'],
 ['Fish',
  ' Chickpeas',
  ' Potato',
  ' Sausage',
  ' Flatbread with Meat',
  ' Banana',
  ' Shampoo',
  ' Beans',
  ' Cookie',
  ' Cheese'],
 ['Chickpeas', ' Rice', ' Dumpling', ' Beans', ' Yogurt', ' Cookie'],
 ['Tomato',
  ' Water',
  ' Pizza',
  ' Honey',
  ' Shampoo',
  ' Lentil',
  ' Detergent',
  ' Chips',
  ' Cracker',
  ' Butter'],
 ['Milk',
  ' Dish Sponge',
  ' Strawberry',
  ' Ice Cream',
  ' Chickpeas',
  ' Shampoo',
  ' Soda',
  ' Cola',
  ' Cheese',
  ' Egg'],
 ['Pizza', ' Water', ' Yogurt', ' Potato', ' Cracker', ' Rice'],
 ['Chicken',
  ' Dumpling',
  ' Tomato',
  ' Lentil',
  ' Cucumber',
  ' Cereal',
  ' Cookie',
  ' Orange'],
 ['Potato', ' Cookie', ' Orange', ' Egg', ' Beans', ' Ice Cream'],
 ['Beans', ' Cereal', ' Butter', ' Honey'],
 ['Dumpling', ' Chocolate', ' Onion', ' Soap'],
 ['Sausage',
  ' Beans',
  ' Ice Cream',
  ' Chocolate',
  ' Shampoo',
  ' Juice',
  ' Dish Sponge'],
 ['Cookie',
  ' Sausage',
  ' Shampoo',
  ' Egg',
  ' Rice',
  ' Water',
  ' Dumpling',
  ' Onion'],
 ['Yogurt',
  ' Cereal',
  ' Sausage',
  ' Cheese',
  ' Bread',
  ' Juice',
  ' Flatbread with Meat',
  ' Strawberry',
  ' Ice Cream'],
 ['Chickpeas', ' Juice', ' Orange'],
 ['Cracker', ' Tomato', ' Beans', ' Orange', ' Ice Cream', ' Lentil'],
 ['Chips', ' Potato', ' Honey', ' Chocolate'],
 ['Banana',
  ' Lentil',
  ' Apple',
  ' Cola',
  ' Pizza',
  ' Shampoo',
  ' Juice',
  ' Dish Sponge',
  ' Sausage'],
 ['Dumpling',
  ' Onion',
  ' Cereal',
  ' Butter',
  ' Detergent',
  ' Banana',
  ' Water',
  ' Chocolate',
  ' Cucumber',
  ' Milk'],
 ['Egg', ' Strawberry', ' Cracker', ' Dish Sponge', ' Potato'],
 ['Sausage', ' Strawberry', ' Yogurt', ' Chicken'],
 ['Ice Cream', ' Tomato', ' Rice'],
 ['Bread', ' Onion', ' Minced Meat'],
 ['Bread', ' Chocolate', ' Sausage', ' Fish', ' Cookie', ' Dumpling'],
 ['Cheese',
  ' Chicken',
  ' Dumpling',
  ' Flatbread with Meat',
  ' Cereal',
  ' Milk',
  ' Minced Meat',
  ' Tomato'],
 ['Flatbread with Meat',
  ' Minced Meat',
  ' Yogurt',
  ' Apple',
  ' Orange',
  ' Chicken',
  ' Egg'],
 ['Potato',
  ' Cucumber',
  ' Soda',
  ' Juice',
  ' Beans',
  ' Cereal',
  ' Cheese',
  ' Bread',
  ' Lentil',
  ' Chicken'],
 ['Honey', ' Potato', ' Pizza', ' Beans', ' Cola', ' Fish', ' Lentil'],
 ['Banana', ' Dumpling', ' Cheese', ' Milk', ' Apple', ' Beans', ' Cereal'],
 ['Detergent',
  ' Chips',
  ' Strawberry',
  ' Chickpeas',
  ' Bread',
  ' Rice',
  ' Milk',
  ' Onion',
  ' Yogurt',
  ' Cola'],
 ['Strawberry',
  ' Cola',
  ' Cereal',
  ' Cracker',
  ' Rice',
  ' Lentil',
  ' Beans',
  ' Ice Cream',
  ' Dumpling',
  ' Yogurt'],
 ['Soda', ' Strawberry', ' Minced Meat'],
 ['Cookie', ' Potato', ' Cheese', ' Beans', ' Chocolate', ' Shampoo', ' Egg'],
 ['Potato', ' Butter', ' Ice Cream'],
 ['Detergent', ' Apple', ' Tomato', ' Water', ' Strawberry', ' Rice'],
 ['Water',
  ' Soap',
  ' Dumpling',
  ' Chickpeas',
  ' Chocolate',
  ' Cucumber',
  ' Minced Meat',
  ' Beans',
  ' Strawberry',
  ' Pizza'],
 ['Bread', ' Dumpling', ' Strawberry'],
 ['Tomato',
  ' Orange',
  ' Chips',
  ' Water',
  ' Beans',
  ' Dumpling',
  ' Cookie',
  ' Chocolate'],
 ['Minced Meat',
  ' Lentil',
  ' Cracker',
  ' Butter',
  ' Rice',
  ' Sausage',
  ' Yogurt',
  ' Cookie',
  ' Tomato'],
 ['Cola', ' Banana', ' Chicken', ' Cereal', ' Soda', ' Beans', ' Onion'],
 ['Chips', ' Soda', ' Chickpeas', ' Soap', ' Honey', ' Chocolate'],
 ['Pizza',
  ' Yogurt',
  ' Egg',
  ' Dish Sponge',
  ' Chickpeas',
  ' Orange',
  ' Water',
  ' Cracker',
  ' Cola'],
 ['Bread',
  ' Soda',
  ' Honey',
  ' Chocolate',
  ' Egg',
  ' Apple',
  ' Lentil',
  ' Pizza',
  ' Orange',
  ' Rice'],
 ['Dish Sponge', ' Lentil', ' Apple', ' Cheese'],
 ['Minced Meat',
  ' Cereal',
  ' Tomato',
  ' Chocolate',
  ' Egg',
  ' Banana',
  ' Onion',
  ' Flatbread with Meat',
  ' Juice',
  ' Soap'],
 ['Strawberry', ' Onion', ' Soda', ' Chicken', ' Yogurt'],
 ['Fish', ' Honey', ' Egg'],
 ['Water',
  ' Butter',
  ' Honey',
  ' Cucumber',
  ' Egg',
  ' Soda',
  ' Milk',
  ' Apple',
  ' Strawberry',
  ' Cookie',
  ' Cereal'],
 ['Ice Cream',
  ' Sausage',
  ' Cucumber',
  ' Milk',
  ' Soap',
  ' Apple',
  ' Strawberry',
  ' Orange',
  ' Water'],
 ['Pizza', ' Water', ' Chocolate', ' Detergent', ' Soap'],
 ['Pizza', ' Bread', ' Rice', ' Ice Cream', ' Dumpling', ' Sausage'],
 ['Apple', ' Strawberry', ' Yogurt', ' Cucumber', ' Rice'],
 ['Cereal', ' Rice', ' Yogurt'],
 ['Ice Cream',
  ' Egg',
  ' Chips',
  ' Juice',
  ' Strawberry',
  ' Onion',
  ' Chickpeas',
  ' Apple'],
 ['Cucumber', ' Ice Cream', ' Sausage'],
 ['Cereal',
  ' Ice Cream',
  ' Shampoo',
  ' Flatbread with Meat',
  ' Butter',
  ' Banana',
  ' Strawberry',
  ' Egg'],
 ['Fish',
  ' Soap',
  ' Detergent',
  ' Lentil',
  ' Yogurt',
  ' Sausage',
  ' Tomato',
  ' Cookie',
  ' Cracker',
  ' Apple'],
 ['Cheese',
  ' Ice Cream',
  ' Bread',
  ' Apple',
  ' Orange',
  ' Shampoo',
  ' Lentil',
  ' Honey'],
 ['Yogurt',
  ' Pizza',
  ' Cheese',
  ' Cola',
  ' Dumpling',
  ' Minced Meat',
  ' Chips'],
 ['Dumpling', ' Cracker', ' Cookie', ' Strawberry', ' Rice'],
 ['Orange', ' Minced Meat', ' Rice', ' Potato'],
 ['Soap',
  ' Chips',
  ' Juice',
  ' Rice',
  ' Cola',
  ' Ice Cream',
  ' Chocolate',
  ' Minced Meat',
  ' Orange',
  ' Cucumber'],
 ['Lentil', ' Butter', ' Potato', ' Soda', ' Chicken'],
 ['Cracker', ' Chickpeas', ' Onion', ' Milk', ' Shampoo', ' Egg'],
 ['Bread',
  ' Milk',
  ' Dish Sponge',
  ' Dumpling',
  ' Cola',
  ' Soda',
  ' Cookie',
  ' Cereal'],
 ['Cookie',
  ' Cheese',
  ' Apple',
  ' Detergent',
  ' Strawberry',
  ' Soda',
  ' Banana',
  ' Tomato',
  ' Chickpeas',
  ' Potato'],
 ['Honey',
  ' Apple',
  ' Potato',
  ' Cola',
  ' Soda',
  ' Dumpling',
  ' Ice Cream',
  ' Chips',
  ' Dish Sponge',
  ' Flatbread with Meat'],
 ['Chocolate', ' Sausage', ' Pizza', ' Shampoo', ' Dumpling'],
 ['Fish',
  ' Detergent',
  ' Honey',
  ' Water',
  ' Flatbread with Meat',
  ' Cucumber'],
 ['Orange', ' Chips', ' Cheese', ' Cracker'],
 ['Potato',
  ' Tomato',
  ' Flatbread with Meat',
  ' Dumpling',
  ' Honey',
  ' Soap',
  ' Detergent',
  ' Dish Sponge'],
 ['Chips', ' Shampoo', ' Soda'],
 ['Cracker',
  ' Banana',
  ' Soap',
  ' Cereal',
  ' Onion',
  ' Milk',
  ' Detergent',
  ' Beans'],
 ['Cheese', ' Soap', ' Milk'],
 ['Cereal',
  ' Yogurt',
  ' Beans',
  ' Fish',
  ' Banana',
  ' Cola',
  ' Minced Meat',
  ' Strawberry',
  ' Sausage',
  ' Egg'],
 ['Apple', ' Soda', ' Minced Meat', ' Dish Sponge', ' Rice', ' Sausage'],
 ['Chips', ' Orange', ' Yogurt', ' Rice', ' Shampoo', ' Soap'],
 ['Cracker',
  ' Soda',
  ' Flatbread with Meat',
  ' Onion',
  ' Tomato',
  ' Minced Meat',
  ' Bread',
  ' Apple',
  ' Cheese',
  ' Yogurt'],
 ['Strawberry', ' Juice', ' Cheese', ' Chips', ' Fish', ' Cookie'],
 ['Cheese',
  ' Minced Meat',
  ' Water',
  ' Dish Sponge',
  ' Dumpling',
  ' Soda',
  ' Yogurt',
  ' Honey',
  ' Fish'],
 ['Cola', ' Fish', ' Bread', ' Chocolate', ' Juice', ' Soap'],
 ['Tomato', ' Apple', ' Chickpeas'],
 ['Cracker', ' Dumpling', ' Soda', ' Milk', ' Egg', ' Chocolate', ' Lentil'],
 ['Apple', ' Honey', ' Chickpeas', ' Soap'],
 ['Orange',
  ' Yogurt',
  ' Soda',
  ' Cracker',
  ' Honey',
  ' Chips',
  ' Soap',
  ' Egg'],
 ['Butter',
  ' Lentil',
  ' Tomato',
  ' Ice Cream',
  ' Onion',
  ' Pizza',
  ' Sausage',
  ' Cracker',
  ' Cola'],
 ['Pizza', ' Butter', ' Cereal', ' Soda', ' Lentil'],
 ['Potato',
  ' Flatbread with Meat',
  ' Dumpling',
  ' Chickpeas',
  ' Strawberry',
  ' Onion',
  ' Pizza',
  ' Fish'],
 ['Milk', ' Ice Cream', ' Yogurt', ' Juice', ' Apple', ' Cola', ' Cereal'],
 ['Sausage', ' Cookie', ' Cereal'],
 ['Orange', ' Rice', ' Egg', ' Onion', ' Soda'],
 ['Pizza', ' Dumpling', ' Detergent'],
 ['Potato', ' Dumpling', ' Yogurt', ' Sausage', ' Banana', ' Chocolate'],
 ['Water',
  ' Juice',
  ' Cucumber',
  ' Tomato',
  ' Chicken',
  ' Onion',
  ' Pizza',
  ' Rice',
  ' Detergent',
  ' Butter'],
 ['Yogurt',
  ' Onion',
  ' Chickpeas',
  ' Chips',
  ' Strawberry',
  ' Juice',
  ' Detergent',
  ' Butter',
  ' Dumpling',
  ' Cola'],
 ['Water',
  ' Apple',
  ' Butter',
  ' Chickpeas',
  ' Tomato',
  ' Detergent',
  ' Pizza'],
 ['Milk',
  ' Shampoo',
  ' Minced Meat',
  ' Beans',
  ' Pizza',
  ' Chicken',
  ' Tomato',
  ' Apple',
  ' Dish Sponge'],
 ['Sausage', ' Banana', ' Soap', ' Cola'],
 ['Sausage',
  ' Strawberry',
  ' Chocolate',
  ' Dumpling',
  ' Chicken',
  ' Chickpeas',
  ' Tomato',
  ' Juice'],
 ['Chocolate', ' Milk', ' Juice'],
 ['Milk', ' Potato', ' Chips', ' Dumpling'],
 ['Cheese', ' Honey', ' Potato', ' Sausage'],
 ['Yogurt',
  ' Strawberry',
  ' Pizza',
  ' Rice',
  ' Egg',
  ' Juice',
  ' Lentil',
  ' Onion',
  ' Potato'],
 ['Butter', ' Banana', ' Shampoo', ' Chips', ' Cucumber'],
 ['Tomato', ' Ice Cream', ' Cereal', ' Chips', ' Chicken', ' Beans'],
 ['Cereal',
  ' Chickpeas',
  ' Soap',
  ' Pizza',
  ' Chicken',
  ' Water',
  ' Egg',
  ' Honey'],
 ['Tomato', ' Cola', ' Beans', ' Fish', ' Minced Meat'],
 ['Orange', ' Cucumber', ' Honey'],
 ['Apple',
  ' Cheese',
  ' Milk',
  ' Cookie',
  ' Lentil',
  ' Cracker',
  ' Detergent',
  ' Orange',
  ' Minced Meat',
  ' Cereal'],
 ['Bread',
  ' Rice',
  ' Water',
  ' Chickpeas',
  ' Flatbread with Meat',
  ' Soap',
  ' Pizza',
  ' Potato',
  ' Detergent',
  ' Dumpling'],
 ['Chips',
  ' Soda',
  ' Rice',
  ' Dish Sponge',
  ' Bread',
  ' Shampoo',
  ' Potato',
  ' Chocolate'],
 ['Honey',
  ' Onion',
  ' Potato',
  ' Soda',
  ' Cucumber',
  ' Tomato',
  ' Chips',
  ' Cola'],
 ['Fish', ' Juice', ' Lentil'],
 ['Apple', ' Sausage', ' Pizza', ' Chips', ' Cookie', ' Bread', ' Juice'],
 ['Chips', ' Apple', ' Potato', ' Yogurt', ' Minced Meat', ' Honey'],
 ['Flatbread with Meat',
  ' Honey',
  ' Chickpeas',
  ' Yogurt',
  ' Dumpling',
  ' Cheese',
  ' Cracker',
  ' Detergent',
  ' Ice Cream',
  ' Potato'],
 ['Chickpeas', ' Chocolate', ' Egg'],
 ['Chocolate', ' Butter', ' Cheese', ' Lentil', ' Honey', ' Rice', ' Bread'],
 ['Dish Sponge',
  ' Milk',
  ' Onion',
  ' Minced Meat',
  ' Beans',
  ' Sausage',
  ' Soda',
  ' Honey',
  ' Cereal'],
 ['Shampoo',
  ' Beans',
  ' Strawberry',
  ' Chicken',
  ' Orange',
  ' Dumpling',
  ' Pizza',
  ' Detergent',
  ' Minced Meat',
  ' Chips'],
 ['Dumpling', ' Rice', ' Strawberry', ' Banana', ' Detergent', ' Minced Meat'],
 ['Yogurt',
  ' Honey',
  ' Beans',
  ' Chocolate',
  ' Detergent',
  ' Fish',
  ' Cola',
  ' Dumpling'],
 ['Strawberry', ' Detergent', ' Chicken', ' Egg'],
 ['Beans',
  ' Bread',
  ' Chocolate',
  ' Orange',
  ' Soda',
  ' Egg',
  ' Honey',
  ' Flatbread with Meat',
  ' Cereal'],
 ['Dish Sponge', ' Dumpling', ' Cracker', ' Cheese'],
 ['Soda',
  ' Beans',
  ' Strawberry',
  ' Cracker',
  ' Cucumber',
  ' Milk',
  ' Cereal',
  ' Chips'],
 ['Yogurt', ' Lentil', ' Flatbread with Meat'],
 ['Milk', ' Chocolate', ' Cola', ' Sausage', ' Shampoo'],
 ['Tomato',
  ' Rice',
  ' Banana',
  ' Water',
  ' Soda',
  ' Cookie',
  ' Chips',
  ' Cola',
  ' Chicken'],
 ['Chicken', ' Cola', ' Cucumber', ' Chocolate', ' Lentil'],
 ['Honey', ' Cereal', ' Yogurt', ' Dish Sponge', ' Rice'],
 ['Onion',
  ' Chickpeas',
  ' Bread',
  ' Egg',
  ' Cucumber',
  ' Minced Meat',
  ' Potato'],
 ['Bread', ' Chocolate', ' Fish', ' Cracker', ' Cookie'],
 ['Cucumber',
  ' Orange',
  ' Apple',
  ' Minced Meat',
  ' Lentil',
  ' Soda',
  ' Chips'],
 ['Bread', ' Cracker', ' Minced Meat', ' Apple'],
 ['Butter',
  ' Water',
  ' Egg',
  ' Detergent',
  ' Banana',
  ' Strawberry',
  ' Soap',
  ' Rice'],
 ['Strawberry',
  ' Bread',
  ' Shampoo',
  ' Soap',
  ' Beans',
  ' Sausage',
  ' Lentil',
  ' Soda',
  ' Fish',
  ' Chocolate'],
 ['Shampoo', ' Lentil', ' Soap', ' Cookie', ' Banana'],
 ['Lentil', ' Tomato', ' Cereal', ' Detergent', ' Strawberry', ' Cucumber'],
 ['Shampoo', ' Detergent', ' Cereal', ' Beans', ' Chickpeas'],
 ['Butter',
  ' Chips',
  ' Flatbread with Meat',
  ' Ice Cream',
  ' Fish',
  ' Onion',
  ' Pizza',
  ' Milk'],
 ['Butter',
  ' Detergent',
  ' Bread',
  ' Dish Sponge',
  ' Chickpeas',
  ' Banana',
  ' Juice',
  ' Cheese',
  ' Shampoo',
  ' Tomato'],
 ['Cola',
  ' Juice',
  ' Fish',
  ' Cheese',
  ' Cookie',
  ' Flatbread with Meat',
  ' Soda'],
 ['Lentil',
  ' Chips',
  ' Butter',
  ' Ice Cream',
  ' Cheese',
  ' Cucumber',
  ' Cola',
  ' Dumpling'],
 ['Orange', ' Juice', ' Soda', ' Water', ' Apple'],
 ['Ice Cream',
  ' Honey',
  ' Rice',
  ' Chicken',
  ' Chocolate',
  ' Strawberry',
  ' Shampoo',
  ' Detergent',
  ' Minced Meat'],
 ['Tomato', ' Cheese', ' Cucumber'],
 ['Chickpeas',
  ' Tomato',
  ' Honey',
  ' Chocolate',
  ' Yogurt',
  ' Chips',
  ' Beans'],
 ['Lentil',
  ' Chickpeas',
  ' Cracker',
  ' Soap',
  ' Juice',
  ' Chocolate',
  ' Tomato',
  ' Pizza',
  ' Cola',
  ' Onion'],
 ['Honey', ' Strawberry', ' Yogurt'],
 ['Bread',
  ' Ice Cream',
  ' Apple',
  ' Dumpling',
  ' Milk',
  ' Dish Sponge',
  ' Shampoo',
  ' Cucumber',
  ' Honey',
  ' Beans'],
 ['Detergent', ' Rice', ' Minced Meat'],
 ['Yogurt', ' Bread', ' Tomato', ' Cracker', ' Pizza', ' Cucumber', ' Soda'],
 ['Dish Sponge',
  ' Water',
  ' Ice Cream',
  ' Orange',
  ' Honey',
  ' Yogurt',
  ' Minced Meat'],
 ['Minced Meat', ' Fish', ' Water', ' Onion', ' Yogurt', ' Apple'],
 ['Cola',
  ' Dish Sponge',
  ' Pizza',
  ' Potato',
  ' Cucumber',
  ' Beans',
  ' Bread',
  ' Lentil'],
 ['Cucumber', ' Milk', ' Dish Sponge', ' Cola', ' Beans', ' Cereal'],
 ['Orange',
  ' Yogurt',
  ' Shampoo',
  ' Lentil',
  ' Bread',
  ' Cracker',
  ' Cheese',
  ' Chickpeas',
  ' Juice',
  ' Chocolate'],
 ['Cereal',
  ' Milk',
  ' Pizza',
  ' Rice',
  ' Soap',
  ' Banana',
  ' Potato',
  ' Cucumber',
  ' Beans'],
 ['Sausage', ' Fish', ' Lentil'],
 ['Water', ' Tomato', ' Cookie', ' Cola', ' Chickpeas'],
 ['Water',
  ' Banana',
  ' Soap',
  ' Flatbread with Meat',
  ' Fish',
  ' Lentil',
  ' Tomato',
  ' Egg'],
 ['Dish Sponge', ' Shampoo', ' Cookie', ' Honey', ' Chips', ' Cola'],
 ['Bread', ' Water', ' Beans', ' Dumpling'],
 ['Rice',
  ' Cheese',
  ' Water',
  ' Yogurt',
  ' Fish',
  ' Minced Meat',
  ' Strawberry',
  ' Onion'],
 ['Potato',
  ' Cola',
  ' Yogurt',
  ' Detergent',
  ' Rice',
  ' Cheese',
  ' Shampoo',
  ' Strawberry',
  ' Milk',
  ' Dish Sponge'],
 ['Soap', ' Juice', ' Flatbread with Meat', ' Chips'],
 ['Strawberry',
  ' Apple',
  ' Chickpeas',
  ' Soap',
  ' Flatbread with Meat',
  ' Potato',
  ' Butter',
  ' Chicken',
  ' Juice',
  ' Sausage'],
 ['Chickpeas',
  ' Cookie',
  ' Potato',
  ' Fish',
  ' Sausage',
  ' Lentil',
  ' Minced Meat',
  ' Cheese'],
 ['Cola', ' Shampoo', ' Banana'],
 ['Bread', ' Soda', ' Cucumber', ' Cola', ' Honey', ' Sausage', ' Potato'],
 ['Tomato', ' Ice Cream', ' Apple'],
 ['Water', ' Potato', ' Chickpeas'],
 ['Banana',
  ' Chips',
  ' Dumpling',
  ' Beans',
  ' Cookie',
  ' Egg',
  ' Detergent',
  ' Strawberry',
  ' Honey',
  ' Cola'],
 ['Cookie',
  ' Butter',
  ' Minced Meat',
  ' Dish Sponge',
  ' Cracker',
  ' Detergent',
  ' Beans',
  ' Soda',
  ' Chickpeas',
  ' Water'],
 ['Shampoo',
  ' Rice',
  ' Cheese',
  ' Fish',
  ' Juice',
  ' Water',
  ' Ice Cream',
  ' Honey'],
 ['Chips', ' Detergent', ' Ice Cream', ' Tomato', ' Cracker'],
 ['Orange', ' Ice Cream', ' Flatbread with Meat', ' Chips', ' Cracker'],
 ['Chocolate', ' Soda', ' Onion', ' Juice', ' Cookie', ' Lentil', ' Cereal'],
 ['Bread',
  ' Water',
  ' Rice',
  ' Cereal',
  ' Lentil',
  ' Chips',
  ' Yogurt',
  ' Minced Meat',
  ' Soap'],
 ['Bread', ' Cookie', ' Flatbread with Meat', ' Dish Sponge', ' Cola'],
 ['Egg', ' Milk', ' Chips', ' Soda', ' Apple', ' Cheese', ' Cereal'],
 ['Cereal',
  ' Dumpling',
  ' Soap',
  ' Minced Meat',
  ' Chocolate',
  ' Butter',
  ' Honey',
  ' Onion',
  ' Chicken',
  ' Chickpeas'],
 ['Soda',
  ' Chicken',
  ' Rice',
  ' Honey',
  ' Butter',
  ' Juice',
  ' Cola',
  ' Dish Sponge',
  ' Egg'],
 ['Cheese', ' Ice Cream', ' Cereal', ' Cookie', ' Cracker'],
 ['Butter', ' Egg', ' Chips', ' Juice'],
 ['Milk', ' Cheese', ' Orange', ' Yogurt'],
 ['Honey',
  ' Detergent',
  ' Beans',
  ' Milk',
  ' Cheese',
  ' Dish Sponge',
  ' Rice',
  ' Fish',
  ' Butter',
  ' Juice',
  ' Cereal'],
 ['Detergent', ' Chicken', ' Banana'],
 ['Egg', ' Chocolate', ' Cola', ' Strawberry', ' Dumpling'],
 ['Strawberry',
  ' Milk',
  ' Dumpling',
  ' Pizza',
  ' Rice',
  ' Soda',
  ' Orange',
  ' Chicken',
  ' Juice'],
 ['Juice', ' Beans', ' Yogurt'],
 ['Dish Sponge', ' Cola', ' Ice Cream', ' Dumpling', ' Shampoo', ' Fish'],
 ['Flatbread with Meat', ' Cookie', ' Cola', ' Water', ' Chickpeas', ' Juice'],
 ['Chickpeas', ' Tomato', ' Rice', ' Bread', ' Cola', ' Strawberry'],
 ['Cookie',
  ' Apple',
  ' Chips',
  ' Soda',
  ' Soap',
  ' Juice',
  ' Beans',
  ' Pizza',
  ' Onion'],
 ['Bread',
  ' Water',
  ' Chocolate',
  ' Dish Sponge',
  ' Milk',
  ' Honey',
  ' Cheese',
  ' Potato',
  ' Cereal'],
 ['Egg',
  ' Apple',
  ' Chickpeas',
  ' Flatbread with Meat',
  ' Cookie',
  ' Butter',
  ' Yogurt',
  ' Water',
  ' Fish'],
 ['Water',
  ' Flatbread with Meat',
  ' Soap',
  ' Apple',
  ' Strawberry',
  ' Dish Sponge',
  ' Milk',
  ' Butter',
  ' Detergent',
  ' Cereal'],
 ['Minced Meat', ' Potato', ' Cracker'],
 ['Water', ' Onion', ' Cheese'],
 ['Onion', ' Apple', ' Cola', ' Strawberry', ' Dumpling', ' Cucumber'],
 ['Bread', ' Strawberry', ' Butter', ' Detergent'],
 ['Shampoo',
  ' Juice',

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
a=TransactionEncoder()
a_data=a.fit(data).transform(data)
df=pd.DataFrame(a_data, columns=a.columns_)

#Turn False & True to 0 & 1 for easy readability
df=df.replace(False,0)
df=df.replace(True,1)

df

/tmp/ipython-input-1545642164.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace(True,1)

,Apple,Banana,Beans,Bread,Butter,Cereal,Cheese,Chicken,Chickpeas,Chips,...,Potato,Rice,Sausage,Shampoo,Soap,Soda,Strawberry,Tomato,Water,Yogurt
0,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,1,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
29996,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
29997,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29998,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29999,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df=apriori(df,min_support=0.02,use_colnames=True)
df

/usr/local/lib/python3.12/dist-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                 itemsets
0    0.136667                 ( Apple)
1    0.138333                ( Banana)
2    0.140000                 ( Beans)
3    0.135833                 ( Bread)
4    0.136833                ( Butter)
..        ...                      ...
257  0.020600  ( Strawberry,  Shampoo)
258  0.020900         ( Soap,  Tomato)
259  0.020400          ( Soap,  Water)
260  0.021567         ( Soap,  Yogurt)
261  0.020433     ( Strawberry,  Soda)

[262 rows x 2 columns]

In [ ]:
df_ar=association_rules(df,metric="confidence", min_threshold=0.3)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,( Cereal),( Milk),0.207833,0.137267,0.076933,0.370168,2.69671,1.0,0.048405,1.369784,0.794249,0.286886,0.269958,0.465317
1,( Milk),( Cereal),0.137267,0.207833,0.076933,0.560466,2.69671,1.0,0.048405,1.802289,0.729284,0.286886,0.445150,0.465317

In [ ]:
df_ar=association_rules(df,metric="lift", min_threshold=1)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,( Apple),( Chickpeas),0.136667,0.138600,0.020500,0.150000,1.082251,1.0,0.001558,1.013412,0.088031,0.080466,0.013234,0.148954
1,( Chickpeas),( Apple),0.138600,0.136667,0.020500,0.147908,1.082251,1.0,0.001558,1.013192,0.088228,0.080466,0.013020,0.148954
2,( Apple),( Dumpling),0.136667,0.137267,0.020367,0.149024,1.085656,1.0,0.001607,1.013817,0.091388,0.080321,0.013628,0.148699
3,( Dumpling),( Apple),0.137267,0.136667,0.020367,0.148373,1.085656,1.0,0.001607,1.013746,0.091451,0.080321,0.013559,0.148699
4,( Apple),( Sausage),0.136667,0.138733,0.020533,0.150244,1.082969,1.0,0.001573,1.013546,0.088740,0.080565,0.013365,0.149125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,( Water),( Soap),0.134200,0.139500,0.020400,0.152012,1.089691,1.0,0.001679,1.014755,0.095067,0.080537,0.014540,0.149124
338,( Soap),( Yogurt),0.139500,0.139867,0.021567,0.154600,1.105337,1.0,0.002055,1.017427,0.110748,0.083657,0.017129,0.154397
339,( Yogurt),( Soap),0.139867,0.139500,0.021567,0.154194,1.105337,1.0,0.002055,1.017373,0.110795,0.083657,0.017077,0.154397
340,( Strawberry),( Soda),0.137800,0.140567,0.020433,0.148283,1.054891,1.0,0.001063,1.009059,0.060351,0.079219,0.008978,0.146823
341,( Soda),( Strawberry),0.140567,0.137800,0.020433,0.145364,1.054891,1.0,0.001063,1.008851,0.060546,0.079219,0.008773,0.146823

In [ ]:
df_ar=association_rules(df,metric="conviction", min_threshold=1.0)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,( Apple),( Chickpeas),0.136667,0.138600,0.020500,0.150000,1.082251,1.0,0.001558,1.013412,0.088031,0.080466,0.013234,0.148954
1,( Chickpeas),( Apple),0.138600,0.136667,0.020500,0.147908,1.082251,1.0,0.001558,1.013192,0.088228,0.080466,0.013020,0.148954
2,( Apple),( Dumpling),0.136667,0.137267,0.020367,0.149024,1.085656,1.0,0.001607,1.013817,0.091388,0.080321,0.013628,0.148699
3,( Dumpling),( Apple),0.137267,0.136667,0.020367,0.148373,1.085656,1.0,0.001607,1.013746,0.091451,0.080321,0.013559,0.148699
4,( Apple),( Sausage),0.136667,0.138733,0.020533,0.150244,1.082969,1.0,0.001573,1.013546,0.088740,0.080565,0.013365,0.149125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,( Water),( Soap),0.134200,0.139500,0.020400,0.152012,1.089691,1.0,0.001679,1.014755,0.095067,0.080537,0.014540,0.149124
338,( Soap),( Yogurt),0.139500,0.139867,0.021567,0.154600,1.105337,1.0,0.002055,1.017427,0.110748,0.083657,0.017129,0.154397
339,( Yogurt),( Soap),0.139867,0.139500,0.021567,0.154194,1.105337,1.0,0.002055,1.017373,0.110795,0.083657,0.017077,0.154397
340,( Strawberry),( Soda),0.137800,0.140567,0.020433,0.148283,1.054891,1.0,0.001063,1.009059,0.060351,0.079219,0.008978,0.146823
341,( Soda),( Strawberry),0.140567,0.137800,0.020433,0.145364,1.054891,1.0,0.001063,1.008851,0.060546,0.079219,0.008773,0.146823